The_Shoe_Tab/The_Shoe_Tab/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

The_Shoe_Tab/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('shoe_tab.urls')),
]

shoe_tab/urls.py
"""Defines URL patters for shoe_tab"""
from django.urls import path
from . import views

app_name = 'shoe_tab'

urlpatterns = [
    path('', views.index, name='index'),
    path('adidas/', views.adidas, name='adidas'),
    path('nike/', views.nike, name='nike'),
    path('air_jordan/', views.air_jordan, name='air_jordan')
]

shoe_tab/models.py
from django.db import models


class Shoe(models.Model):
    """The Shoe class for acessing and putting in new shoe data"""
    shoe_brand = models.CharField(max_length=16)                # shoe brand for filtering
    shoe_name = models.CharField(max_length=128, unique=True)   # name of the shoe
    release_day = models.IntegerField()                         # release day field
    release_month = models.IntegerField()                       # release month field
    release_year = models.IntegerField()                        # release year field
    release_time = models.CharField(max_length=16)              # release time
    image = models.URLField()                                   # image url
    price = models.CharField(max_length=16)                     # drop price
    hyped = models.BooleanField()                               # if shoe is hyped or not

shoe_tab/views.py
from django.shortcuts import render
from django.http import JsonResponse
from shoe_tab.getShoeData import gate
from shoe_tab.getShoeData import allData


def index(request):
    """The home page for the shoe tab"""
    return render(request, 'shoe_tab/index.html', {'dataBlock': allData()})


def adidas(request):
    """Shows all adidas releases"""
    allReleases, hyped = gate("Adidas")
    return render(request, 'shoe_tab/adidas.html', {'releases': allReleases, 'hyped': hyped})


def nike(request):
    """Shows all Nike releases"""
    allReleases, hyped = gate("Nike")
    return render(request, 'shoe_tab/nike.html', {'releases': allReleases, 'hyped': hyped})


def air_jordan(request):
    """Shows all jordan releases"""
    allReleases, hyped = gate("Air Jordan")
    return render(request, 'shoe_tab/air_jordan.html', {'releases': allReleases, 'hyped': hyped})


def calender(request):
    """Will contain a calender of everything in the database"""

shoe_tab/templates/shoe_tab/adidas.html
{% extends "shoe_tab/base.html" %}

{% block content %}

<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>
    <a href= "{% url 'shoe_tab:index' %}" class = "w3-bar-item w3-button">Home Page</a>
    <a href= "{% url 'shoe_tab:nike' %}" class = "w3-bar-item w3-button">Nike</a>
    <a href= "{% url 'shoe_tab:air_jordan' %}" class = "w3-bar-item w3-button">Air Jordan</a>
</nav>


<h5 class = 'TitleHeader'>Adidas</h5>
<hr>

<div id = "tab" class = "w3-top">
    <div class="w3-white w3-xlarge" id = "elipses"></div>
    <div id = "elipsesVert" class="w3-button w3-padding-16 w3-left" onclick="w3_open()"><i class="fa fa-bars" style="font-size:36px;"></i></div>   
</div>

{% if hyped %}
    <h5 style = "text-align: center;">Hyped Releases</h5>
    <div class = "container">
        {% for key in hyped %}
            <div class = "card">
                <div title="Add to Calendar" class="addeventatc">
                    Add to Calendar
                    <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="timezone">America/Los_Angeles</span>
                    <span class="alarm_reminder">15</span>
                    <span class="title">Summary of the event</span>
                    <span class="description">Description of the event</span>
                    <span class="location">Location of the event</span>
                </div>
                <h5>{{ key.shoe_name }}</h5>
                {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                    <img src = {{ key.image }}>
                {% else %}
                    <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
                {% endif %}
                <h5>Price: {{ key.price }}</h5>
                <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
                
            </div>
        {% endfor %}
    </div>
{% endif %}


<h5 style = "text-align: center;">Upcoming Releases</h5>
<div class = "container">
    {% for key in releases %}
        <div class = "card">
            <div title="Add to Calendar" class="addeventatc">
                Add to Calendar
                <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="timezone">America/Los_Angeles</span>
                <span class="alarm_reminder">15</span>
                <span class="title">Summary of the event</span>
                <span class="description">Description of the event</span>
                <span class="location">Location of the event</span>
            </div>
            <h5>{{ key.shoe_name }}</h5>
            {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                <img src = {{ key.image }}>
            {% else %}
                <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
            {% endif %}
            <h5>Price: {{ key.price }}</h5>
            <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
        </div>
    {% endfor %}
</div>

{% endblock content %}

shoe_tab/templates/shoe_tab/air_jordan.html
{% extends "shoe_tab/base.html" %}
{% block content %}

<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>
    <a href= "{% url 'shoe_tab:index' %}" class = "w3-bar-item w3-button">Home Page</a>
    <a href= "{% url 'shoe_tab:nike' %}" class = "w3-bar-item w3-button">Nike</a>
    <a href= "{% url 'shoe_tab:adidas' %}" class = "w3-bar-item w3-button">Adidas</a>
</nav>

<h5 class = 'TitleHeader'>Air Jordan</h5>
<hr>

<div id = "tab" class = "w3-top">
    <div class="w3-white w3-xlarge" id = "elipses"></div>
    <div id = "elipsesVert" class="w3-button w3-padding-16 w3-left" onclick="w3_open()"><i class="fa fa-bars" style="font-size:36px;"></i></div>   
</div>

{% if hyped %}
    <h5 style = "text-align: center;">Hyped Releases</h5>
    <div class = "container">
        {% for key in hyped %}
            <div class = "card">
                <div title="Add to Calendar" class="addeventatc">
                    Add to Calendar
                    <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="timezone">America/Los_Angeles</span>
                    <span class="alarm_reminder">15</span>
                    <span class="title">Summary of the event</span>
                    <span class="description">Description of the event</span>
                    <span class="location">Location of the event</span>
                </div>
                <h5>{{ key.shoe_name }}</h5>
                {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                    <img src = {{ key.image }}>
                {% else %}
                    <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
                {% endif %}
                <h5>Price: {{ key.price }}</h5>
                <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
                
            </div>
        {% endfor %}
    </div>
{% endif %}


<h5 style = "text-align: center;">Upcoming Releases</h5>
<div class = "container">
    {% for key in releases %}
        <div class = "card">
            <div title="Add to Calendar" class="addeventatc">
                Add to Calendar
                <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="timezone">America/Los_Angeles</span>
                <span class="alarm_reminder">15</span>
                <span class="title">Summary of the event</span>
                <span class="description">Description of the event</span>
                <span class="location">Location of the event</span>
            </div>
            <h5>{{ key.shoe_name }}</h5>
            {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                <img src = {{ key.image }}>
            {% else %}
                <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
            {% endif %}
            <h5>Price: {{ key.price }}</h5>
            <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
        </div>
    {% endfor %}
</div>

{% endblock content %}

shoe_tab/templates/shoe_tab/base.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://fonts.googleapis.com/css?family=Advent+Pro&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    body, html{
        position:relative !important;
        height: 100% !important;
        font-family: "Advent Pro", sans-serif !important; 
        background-color: #D3D3D3 !important;
    }
    .bgimg {
        background-position: center;
        background-size: cover;
        background-image: url();
        min-height: 75%;
    }

    .menu {
        display: none;
    }

    #body{
        background-color: #D3D3D3;
    }
    .card {
        background-color: #F5F5Ee;
        border-radius: 100%;
        text-align: center;
        transition: 0.3s;
        width: 29%;
        border-radius: 5px;
        float: left;
        margin-left: 20px;
        margin-right: 20px;
        margin-top: 10px;
        padding-left: 5px;
        padding-right: 5px; 
    }
    .addeventatc:hover{
        background-color: #751710!important;
        color: white!important;
    }
    .addeventatc{
        z-index: 2!important;
        width: 100%
    }
    .container{
        width: 95%;
        display:flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
    }
    img{
        width: 100%;
        height: 35%;
    }
    h5{
        font-size: 20px;
    }

    .TitleHeader{
        text-align: center;
        font-size: 36px;
    }

    #elipsesVert{
        background-color: #D3D3D3;
    }
    .prev, .next {
    cursor: pointer;
    position: absolute;
    top: 50%;
    width: auto;
    padding: 16px;
    margin-top: -22px;
    color:white;
    font-weight: bold;
    font-size: 18px;
    transition: 0.6s ease;
    border-radius: 0 3px 3px 0;
    user-select: none;
    }

    .next{
        right: 0;
        border-radius: 3px 0 0 3px;
    }

    .prev:hover .next:hover{
        background-color: #f1f1f1;
        color: blac;
    }

    .d-block.w-100{
        vertical-align: middle;
        width:1000px !important;
        height:550px !important;
    }
    #logo{
        height: 50%;
    }
</style>

{% block content %}

    {{ body }}

{% endblock content %}

<script>
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
    }
        
    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
    }
</script>

shoe_tab/templates/shoe_tab/index.html
{% extends "shoe_tab/base.html" %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:300px" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>
    <a href= "{% url 'shoe_tab:nike' %}" class = "w3-bar-item w3-button">Nike</a>
    <a href= "{% url 'shoe_tab:air_jordan' %}" class = "w3-bar-item w3-button">Air Jordan</a>
    <a href= "{% url 'shoe_tab:adidas' %}" class = "w3-bar-item w3-button">Adidas</a>
</nav>

<h5 class = 'TitleHeader'>Home Page</h5>
<hr>

<div id = "tab" class = "w3-top">
    <div class="w3-white w3-xlarge" id = "elipses"></div>
    <div id = "elipsesVert" class="w3-button w3-padding-16 w3-left" onclick="w3_open()"><i class="fa fa-bars" style="font-size:36px;"></i></div>   
</div>

<div class= "container">
  <img id = "logo" src = "https://raw.githubusercontent.com/GhazanfarShahbaz/unfinished_small_projects/master/The%20Shoe%20Tab/logo/The%20Shoe%20Tab-logo%20(4).png?token=AJZNVVN2BFJ55PQZWURIUH27MRBG4">
</div>

<div class = "container" style= "width: 80%;">
    <div id="carouselExample" class="carousel slide" data-ride="carousel">
            
        <ol class="carousel-indicators">
          <li data-target="#carouselExample" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExample" data-slide-to="1"></li>
          <li data-target="#carouselExample" data-slide-to="2"></li>
        </ol>

        <div  class = "carousel-inner">
        {% for data in dataBlock|slice:"3" %}
            {% if data == dataBlock.first  %}
                <div class="carousel-item active">
                    <img class="d-block w-100" src= {{ data.image }}>
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
            {% else %}
                <div class="carousel-item">
                    <img class="d-block w-100" src= {{ data.image }}>
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
            {% endif %}
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
  </div>
</div>

<script src="js/jquery-1.7.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>    
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>    
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


{% endblock content %}

shoe_tab/templates/shoe_tab/nike.html
{% extends "shoe_tab/base.html" %}
{% block content %}

<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:20%;min-width:300px" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button">Close Menu</a>
    <a href= "{% url 'shoe_tab:index' %}" class = "w3-bar-item w3-button">Home Page</a>
    <a href= "{% url 'shoe_tab:air_jordan' %}" class = "w3-bar-item w3-button">Air Jordan</a>
    <a href= "{% url 'shoe_tab:adidas' %}" class = "w3-bar-item w3-button">Adidas</a>
</nav>

<h5 class = 'TitleHeader'>Nike</h5>
<hr>

<div id = "tab" class = "w3-top">
    <div class="w3-white w3-xlarge" id = "elipses"></div>
    <div id = "elipsesVert" class="w3-button w3-padding-16 w3-left" onclick="w3_open()"><i class="fa fa-bars" style="font-size:36px;"></i></div>   
</div>

{% if hyped %}
    <h5 style = "text-align: center;">Hyped Releases</h5>
    <div class = "container">
        {% for key in hyped %}
            <div class = "card">
                <div title="Add to Calendar" class="addeventatc">
                    Add to Calendar
                    <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                    <span class="timezone">America/Los_Angeles</span>
                    <span class="alarm_reminder">15</span>
                    <span class="title">Summary of the event</span>
                    <span class="description">Description of the event</span>
                    <span class="location">Location of the event</span>
                </div>
                <h5>{{ key.shoe_name }}</h5>
                {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                    <img src = {{ key.image }}>
                {% else %}
                    <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
                {% endif %}
                <h5>Price: {{ key.price }}</h5>
                <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
                
            </div>
        {% endfor %}
    </div>
{% endif %}


<h5 style = "text-align: center;">Upcoming Releases</h5>
<div class = "container">
    {% for key in releases %}
        <div class = "card">
            <div title="Add to Calendar" class="addeventatc">
                Add to Calendar
                <span class="start">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="end">{{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</span>
                <span class="timezone">America/Los_Angeles</span>
                <span class="alarm_reminder">15</span>
                <span class="title">Summary of the event</span>
                <span class="description">Description of the event</span>
                <span class="location">Location of the event</span>
            </div>
            <h5>{{ key.shoe_name }}</h5>
            {% if key.image != "https://images.solecollector.com/complex/image/upload/v1557176412/SC_Logo_Globe_TM_Blue_20190506-01-01-01_urcggx.svg" %}
                <img src = {{ key.image }}>
            {% else %}
                <img src = "https://www.reaganfoundation.org/umbraco/ucommerce/images/ui/image_not_found.jpg">
            {% endif %}
            <h5>Price: {{ key.price }}</h5>
            <h5>Release Date: {{ key.release_month }}/{{ key.release_day }}/{{ key.release_year }}</h5>
        </div>
    {% endfor %}
</div>

{% endblock content %}